declare module "@phosphor-icons/react" {
  import type { ComponentType, SVGProps } from "react";

  export type Icon = ComponentType<SVGProps<SVGSVGElement> & {
    size?: number | string;
    weight?: string;
    color?: string;
    mirrored?: boolean;
  }>;

  export const Activity: Icon;
  export const Archive: Icon;
  export const ArrowLeft: Icon;
  export const CaretDown: Icon;
  export const CaretRight: Icon;
  export const ChartLine: Icon;
  export const CheckCircle: Icon;
  export const ClipboardText: Icon;
  export const Clock: Icon;
  export const ClockCounterClockwise: Icon;
  export const Eye: Icon;
  export const EyeSlash: Icon;
  export const File: Icon;
  export const FileArrowUp: Icon;
  export const FileText: Icon;
  export const Gear: Icon;
  export const House: Icon;
  export const ListChecks: Icon;
  export const LockKey: Icon;
  export const MagnifyingGlass: Icon;
  export const MagnifyingGlassMinus: Icon;
  export const MagnifyingGlassPlus: Icon;
  export const Package: Icon;
  export const Plus: Icon;
  export const ShieldCheck: Icon;
  export const SignOut: Icon;
  export const SidebarSimple: Icon;
  export const SpinnerGap: Icon;
  export const Storefront: Icon;
  export const UserList: Icon;
  export const Users: Icon;
  export const UsersThree: Icon;
  export const Warning: Icon;
  export const WarningCircle: Icon;
  export const WarningOctagon: Icon;
  export const X: Icon;

  export const ActivityIcon: Icon;
  export const ArchiveIcon: Icon;
  export const ArrowLeftIcon: Icon;
  export const ArrowsClockwiseIcon: Icon;
  export const CaretDownIcon: Icon;
  export const CaretRightIcon: Icon;
  export const ChartLineIcon: Icon;
  export const CopyIcon: Icon;
  export const CheckCircleIcon: Icon;
  export const ClipboardTextIcon: Icon;
  export const ClockIcon: Icon;
  export const ClockCounterClockwiseIcon: Icon;
  export const EyeIcon: Icon;
  export const EyeSlashIcon: Icon;
  export const FileIcon: Icon;
  export const FileArrowUpIcon: Icon;
  export const FileTextIcon: Icon;
  export const FunnelIcon: Icon;
  export const GearIcon: Icon;
  export const HouseIcon: Icon;
  export const ListChecksIcon: Icon;
  export const LockKeyIcon: Icon;
  export const MagnifyingGlassIcon: Icon;
  export const MagnifyingGlassMinusIcon: Icon;
  export const MagnifyingGlassPlusIcon: Icon;
  export const PackageIcon: Icon;
  export const PlugsConnectedIcon: Icon;
  export const PlayIcon: Icon;
  export const PulseIcon: Icon;
  export const PlusIcon: Icon;
  export const QueueIcon: Icon;
  export const ShieldCheckIcon: Icon;
  export const SignOutIcon: Icon;
  export const SidebarSimpleIcon: Icon;
  export const SpinnerGapIcon: Icon;
  export const StorefrontIcon: Icon;
  export const UserListIcon: Icon;
  export const UsersIcon: Icon;
  export const UsersThreeIcon: Icon;
  export const WarningIcon: Icon;
  export const WarningCircleIcon: Icon;
  export const WarningOctagonIcon: Icon;
  export const WebhooksLogoIcon: Icon;
  export const XIcon: Icon;
}
